apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service-green  # Initially set to green
  ports:
  - protocol: TCP
    port: 83
    targetPort: 50002
  type: ClusterIP
