apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service-green
  template:
    metadata:
      labels:
        app: notification-service-green
    spec:
      containers:
      - name: notification-service
        image: gcr.io/healthsync-project-445302/notification-service:latest
        ports:
        - containerPort: 5002
        readinessProbe:
          httpGet:
            path: /api/v1/notification-service/readiness
            port: 5002
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/v1/notification-service/healthcheck
            port: 5002
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
        - name: MONGO_URI
          value: "mongodb+srv://navodasathsarani:chQf3ctN1Xwx7H6s@health-sync-mongo-db.okigg.mongodb.net/health-db?retryWrites=true&w=majority&appName=health-sync-mongo-db"
